### ISSUE TITLE
androidx.recyclerview.widget.RecyclerView cannot be cast to rikka.widget.borderview.BorderRecyclerView

### ISSUE THREAD

**Issue by OrdinarySK** [RikkaApps/RikkaX#22]
`java.lang.ClassCastException: androidx.recyclerview.widget.RecyclerView cannot be cast to rikka.widget.borderview.BorderRecyclerView
        at com.sk.ordinary.fragment.SettingsFragment$PreferenceFragment.onCreateRecyclerView(SettingsFragment.java:167)`

The reference code is to use val to receive in kotlin. Can I write it before java jdk11. i.e. don't use var.

**Comment by OrdinarySK** [comment]
The way I rewrite the var reception of jdk11 is still the same problem.....

**Comment by OrdinarySK** [comment]
Here are my code:`public RecyclerView onCreateRecyclerView(@NonNull LayoutInflater inflater, @NonNull ViewGroup parent, Bundle savedInstanceState) {
            BorderRecyclerView recyclerView =  (BorderRecyclerView)super.onCreateRecyclerView(inflater, parent, savedInstanceState);
return recyclerView}`  or  replace the BorderRecyclerView to var, the same error. I

**Comment by RikkaW** [comment]
Application can override library resource files by creating files with the same name. Here is an example, so the RecyclerView becomes BorderRecyclerView.

https://github.com/RikkaApps/Shizuku/blob/83f3076c433a426dcbde5f9701148779756c20ee/manager/src/main/res/layout/preference_recyclerview.xml

**Comment by OrdinarySK** [comment]
OK, Thanks. I need to use `BorderRecyclerView ` scroll to the top. I will  try using the method you provided.
