### ISSUE TITLE
MOmo4.4.1    环境正常，但是反诈中心打不开

### ISSUE THREAD

**Issue by LHC12580** [RikkaApps/RikkaX#30]
反诈中心 最新版，打不开。

MOmo检测目前需要更新新检测机制版本了。

**Comment by haruue** [comment]
提错地方了。 建议用 Google 搜索 你使用的软件名称+GitHub 来寻找正确的仓库提交你的 Issue。

**Comment by LHC12580** [comment]
Momo检测机制就不应该公开，因为公开了，现在官方针对root设备检测。现在很多Momo环境检测没有问题，但是软件就就是用不了！最新工商银行被检测出来，支付宝也不能刷脸！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月7日(周二) 中午1:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RikkaApps/RikkaX] MOmo4.4.1    环境正常，但是反诈中心打不开 (Issue #30)




 
提错地方了。 建议用 Google 搜索 你使用的软件名称+GitHub 来寻找正确的仓库提交你的 Issue。
