### ISSUE TITLE
How to use this libarry

### ISSUE THREAD

**Issue by Android1500** [RikkaApps/RikkaX#7]
Actually i like your material design libary and i want to making my new xposed module and i want to make ui like your app shizku so how can use these libary? It will help me alot

**Comment by SwQQQ** [comment]
I have the same question😂

**Comment by Android1500** [comment]
> I have the same question😂

We can use it by just read his shizuku app git but i want a proper implimation guide

**Comment by Revincx** [comment]
> Actually i like your material design libary and i want to making my new xposed module and i want to make ui like your app shizku so how can use these libary? It will help me alot

The same question😂,the material ui is so elegant !

**Comment by ryuunoakaihitomi** [comment]
Note: The doc of [RikkaX InsetsHelper](https://github.com/RikkaApps/RikkaX/blob/master/insets/README.md) has been released.

**Comment by Android1500** [comment]
> Note: The doc of [RikkaX InsetsHelper](https://github.com/RikkaApps/RikkaX/blob/master/insets/README.md) has been released.

Thanks for Update

**Comment by ryuunoakaihitomi** [comment]
Note: [ParcelableList](https://github.com/RikkaApps/RikkaX/tree/master/parcelablelist#readme)
